version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    volumes:
      - database-volume:/var/lib/postgresql/data
    container_name: vocabulary-db
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    networks:
       - voc-net
    healthcheck:
      test: pg_isready -U ${DB_USERNAME} -q -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 3

  vocabulary:
    build: .
    container_name: vocabulary
    env_file: .env
    restart: always
    depends_on:
      - database
    ports:
       - 127.0.0.1:${API_PORT}:8000
    entrypoint: ["uvicorn", "vocabulary.main:app", "--port", "8000",
                 "--host", "0.0.0.0", "--loop", "uvloop"]
    networks:
      - voc-net
    healthcheck:
      test: curl -f http://localhost:8000/words/to-learn/list || exit 1
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  database-volume:

networks:
  voc-net:
