version: '3'

services:
  database:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - database-volume:/var/lib/postgresql/data
    container_name: database
    networks:
       - voc-net
    healthcheck:
        test: "exit 0"

  vocabulary:
    build: .
    container_name: "vocabulary"
    depends_on:
       - database
    ports:
       - 127.0.0.1:${API_PORT}:8000
    entrypoint: ["uvicorn", "vocabulary.main:app", "--port", "8000",
                 "--host", "0.0.0.0", "--loop", "uvloop"]
    networks:
      - voc-net
    healthcheck:
        test: "exit 0"
    depends_on:
      - database

volumes:
  database-volume:

networks:
  voc-net:
